<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UserSecretsId>2ac6ce7f-deda-4c20-aec1-0d8a253194a1</UserSecretsId>
    <ApplicationIcon>vabel_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Res\Fonts\MaterialSymbolsRounded.ttf" />
    <None Remove="Res\Images\vabel_dark.png" />
    <None Remove="Res\Images\vabel_icon.ico" />
    <None Remove="Res\Images\vabel_white.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="vabel_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Res\Fonts\MaterialSymbolsRounded.ttf" />
    <Resource Include="Res\Images\vabel_dark.png" />
    <Resource Include="Res\Images\vabel_icon.ico" />
    <Resource Include="Res\Images\vabel_white.png" />
  </ItemGroup>

</Project>
